### ISSUE TITLE
Add Playwrights sample to template gallery

### ISSUE THREAD

**Issue by ilovan** [cwrc/CWRC-Writer#363]
Label to display on the CWRC landing page:
"Sample Canadian Women Playwrights entry"

XML document to use: https://www.dropbox.com/s/27swljbu3p0ykvu/McIntyre%2C%20Hope%20%2804%29%20VR2.xml?dl=0

CSS to use: http://cwrc.ca/templates/css/playwrights-CWRCWriter.css

**Comment by ajmacdonald** [comment]
This has been added now.
NB: I've finally been able to implement automatic CSS conversion, which greatly improves the flexibility of CWRC-Writer.
However, this means that the CSS specified in the playwrights template ( http://cwrc.ca/templates/css/playwrights.css ) needs to be fixed, as it contains a syntax error:
```
CHRONPROSE{
    display:table-cell; /*border:solid*/;
    line-height:150%
}
```

**Comment by ajmacdonald** [comment]
To be clear, this means we no longer need to produce our own converted versions of the CSS files.

**Comment by SusanBrown** [comment]
wonderful!!

**Comment by ilovan** [comment]
I can see the template, but the style sheet doesn't seem to be available. 
![screen shot 2015-10-16 at 4 37 29 pm](https://cloud.githubusercontent.com/assets/6600070/10554846/6c7e3498-7424-11e5-89a1-60cd0b6f5b7d.png)

**Comment by ajmacdonald** [comment]
The style sheet needs to be updated to fix the syntax error that I mentioned here: https://github.com/cwrc/CWRC-Writer/issues/363#issuecomment-144203376

After that's done, the style sheet should display properly.

**Comment by ilovan** [comment]
Hi Andrew, I fixed the stylesheet about an hour or so ago.

**Comment by ajmacdonald** [comment]
Hi Mihaela, I'm looking at the http://cwrc.ca/templates/css/playwrights.css file and it still shows an extra semi-colon after the commented out border style. This is messing up the CSS conversion.

**Comment by ilovan** [comment]
Sorry Andrew, I had applied the fix to a different version of the css by mistake. 
It should be fixed now.

Quick question about the automatic css conversion you mentioned: 

Does this mean that from now on the css declaration in the xml document is automatically used by CWRC-Writer, or only that the grammar of the css doesn't need to be modified to be recognizable by CWRC-Writer?

Example: 

```DOCAUTHOR{
    font-weight:bold
}```

replaced with 

```*[_tag="DOCAUTHOR"]{
    font-weight:bold
}```

**Comment by ajmacdonald** [comment]
It looks fixed to me.

The css declaration in the xml document IS automatically used by CWRC-Writer. And the conversion is also performed by CWRC-Writer.

**Comment by susanirenebrown** [comment]
That is fabulous in both counts.
